https://deepage.net/features/numpy-eigenvalue-vector.html

In [1]:
import numpy as np

In [2]:
import numpy.linalg as LA

In [22]:
a = np.array([[1, 3],[2, 2]])

In [25]:
a

array([[1, 3],
       [2, 2]])

In [26]:
LA.eig(a)

(array([-1.,  4.]),
 array([[-0.83205029, -0.70710678],
        [ 0.5547002 , -0.70710678]]))

In [27]:
-0.832*4

-3.328

In [28]:
0.55*4

2.2